### ISSUE TITLE
Filechooser doesn't show any files at all

### ISSUE THREAD

**Issue by gkarsay** [flathub/com.github.gkarsay.parlatype#1]
This issue was created by @elya5 in parlatype's repository, I'm moving (copy & paste) it here:

### Installation and version

How did you install Parlatype?
From flathub (flatpak version 0.10.0)

### Your desktop environment

* What's your distro? Fedora 27
* What's your desktop environment? GNOME

### Issue

* What is not working as expected? If I click the "open" button, the file chooser dialog does not show any files or directories
* Does it happen all the time? Yes
* If you start Parlatype from terminal, is there any error output? There is no output

### Other information
![screenshot of empty filechooser](https://user-images.githubusercontent.com/4464481/32862338-1337b0b2-ca58-11e7-8974-ced114ff3b54.png)

**Comment by gkarsay** [comment]
Confirmed, it works with `flatpak run --filesystem=home com.github.gkarsay.parlatype` for me. I'm going to update it.

**Comment by elya5** [comment]
Thanks! 👍
