### ISSUE TITLE
should be in audio

### ISSUE THREAD

**Issue by matthiasclasen** [flathub/com.github.gkarsay.parlatype#2]
Parlatype shows up in Utilities on flathub, which I find a bit surprising, since it calls itself a media player. I would have expected it under Audio.

**Comment by gkarsay** [comment]
I have no objections changing the category. Is this something I can change myself? I don't know where.

**Comment by gkarsay** [comment]
Fixed with version 1.5.6; upstream commit https://github.com/gkarsay/parlatype/commit/eb284ad60186a66f00a42d9eabcd321bf9c33b11
